baseURL = "https://taha2053.github.io/ATK-LOG.github.io/blog/"

languageCode = "en-us"
title = "🍊 ATK'Log"
theme = "PaperMod"

disableHugoGeneratorInject = true

[params.assets]
disableFingerprinting = true


[params]
  author = "Almouthana Taha Khalfallah"
  showReadingTime = true
  disableHugoGeneratorInject = true



[menu]
  [[menu.main]]
  name = "Home"
  url = "https://taha2053.github.io/ATK-LOG.github.io/"
  weight = 1

  [[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

  [[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3





